approvedGitRepositories:
  - "**"

cacheFolder: .yarn/cache

compressionLevel: 9

enableGlobalCache: false

enableMirror: false

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 0
