# Specify the location for the Yarn cache
cacheFolder: .yarn/cache

# Set the compression level for cached files (1 = fastest, 9 = smallest size)
compressionLevel: 9

# Use a global cache for dependencies (set to true for shared caching across projects)
enableGlobalCache: false

# Enable or disable the global mirror for dependencies
enableMirror: false

# Disable telemetry to prevent sending anonymous usage data
enableTelemetry: false

# Use the traditional node_modules folder for dependency installation
nodeLinker: node-modules

# Specify the Yarn version to use for this project
yarnPath: .yarn/releases/yarn-4.8.1.cjs
